version: '3.8'
services:
    php-apache-environment:
        container_name: reticula-php
        build:
            context: ./src
            dockerfile: DockerFile
        depends_on:
            - db
        volumes:
            - ./src:/var/www/html/
        ports:
            - 80:80
    db:
      container_name: reticula-db
      image: mysql
      restart: always
      environment:
          MYSQL_ROOT_PASSWORD: " " 
          MYSQL_DATABASE: "reticula"
          MYSQL_USER: "erick"
          MYSQL_PASSWORD: " "
      ports:
        - "9906:3306"